# Generated by Django 6.1.2 on 2026-10-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='precio',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='stock',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
