# Generated by Django 6.1.2 on 2026-10-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0002_plan_precio_plan_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparacion',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='stock',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
